name: freecad
base: core24
adopt-info: freecad
donation: https://wiki.freecad.org/Donate
issues: https://github.com/FreeCAD/FreeCAD-snap/issues
website: https://freecad.org
summary: An open source parametric 3D CAD modeler
description: |
  FreeCAD is a parametric 3D modeler. Parametric modeling
  allows you to easily modify your design by going back into
  your model history and changing its parameters. FreeCAD is
  open source (LGPL license) and completely modular, allowing
  for very advanced extension and customization.

  FreeCAD is multiplatfom, and reads and writes many open
  file formats such as STEP, IGES, STL and others.

  Commands:
        freecad:      Run FreeCAD
        freecad.cmd:  Run FreeCAD command line interface
        freecad.pip:  Install python packages for user (not system-wide).
                      E.g. `freecad.pip install py_slvs` for Assembly3.

grade: devel
confinement: strict
compression: lzo
license: LGPL-2.0-or-later

layout:
  # --- Layouts for ElmerFEM / OpenMPI ---
  /usr/share/elmersolver: # For Elmer's own data files (e.g., elements.def)
    bind: $SNAP/usr/share/elmersolver
  /usr/bin/mpirun: # For MPI commands like 'mpirun'
    symlink: $SNAP/usr/bin/orterun
  /usr/share/openmpi: # For OpenMPI's help/data files
    symlink: $SNAP/usr/share/openmpi
  /etc/openmpi: # For OpenMPI's system-wide configuration
    bind: $SNAP/etc/openmpi
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/openmpi: # For OpenMPI's component plugins
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/openmpi
  /usr/bin/orted: # For the OpenMPI runtime daemon
    symlink: $SNAP/usr/bin/orted
  /usr/share/pmix: # For PMIX (an OpenMPI dependency) data files
    symlink: $SNAP/usr/share/pmix
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pmix: # For PMIX libraries
    symlink: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pmix

  # --- Layouts for other FreeCAD Dependencies ---
  /etc/matplotlibrc: # For Matplotlib's configuration
    bind-file: $SNAP/etc/matplotlibrc
  /usr/share/matplotlib: # For Matplotlib's data files (fonts, styles)
    symlink: $SNAP/usr/share/matplotlib
  /usr/bin/dot: # For Graphviz (dependency graph)
    symlink: $SNAP/kf6/usr/bin/dot
  /usr/bin/unflatten: # For Graphviz (dependency graph)
    symlink: $SNAP/kf6/usr/bin/unflatten
  /usr/share/povray-3.7: # For POV-Ray (raytracing workbench)
    symlink: $SNAP/usr/share/povray-3.7

plugs:
  # this is not used or needed for anything other than to trigger automatic
  # installation of the cups snap via "default-provider: cups"
  foo-install-cups:
    interface: content
    content: foo
    default-provider: cups
    target: $SNAP_DATA/foo
  # Necessary to enable semaphores for numba, OpenMP etc.
  shared-memory:
    private: true

environment:
  LD_LIBRARY_PATH: "$SNAP/usr/lib/:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/:$SNAP/kf6/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/:$SNAP/kf6/usr/lib:/$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/blas:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/lapack:$LD_LIBRARY_PATH"
  LD_PRELOAD: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libstubchown.so
  FREECAD_USER_HOME: $SNAP_USER_COMMON
  GIT_EXEC_PATH: $SNAP/usr/lib/git-core
  GIT_TEMPLATE_DIR: $SNAP/usr/share/git-core/templates
  GIT_CONFIG_NOSYSTEM: "1"
  ELMER_HOME: $SNAP/usr
  PYTHONPYCACHEPREFIX: $SNAP_USER_COMMON/.pycache
  PYTHONUSERBASE: $SNAP_USER_COMMON/.local
  PIP_USER: "1"
  PIP_BREAK_SYSTEM_PACKAGES: "1"
  PYTHONPATH: &pypath $PYTHONUSERBASE/lib/python3.12/site-packages:$SNAP/lib/python3.12/site-packages:$SNAP/usr/lib/python3/dist-packages
  SNAP_PYTHONPATH: *pypath
  GVBINDIR: "$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/graphviz-runtime"
  WAYLAND_DISPLAY: unset # https://forum.snapcraft.io/t/kde-neon-6-extension-snap-qt-qpa-platform-overwritten/46054/8
  POVINI: $SNAP/etc/povray/3.7/povray.ini # Raytracing

apps:
  freecad:
    command: usr/bin/FreeCAD
    extensions: [kde-neon-6]
    common-id: org.freecad.FreeCAD.desktop
    desktop: usr/share/applications/org.freecad.FreeCAD.desktop
    plugs: &plugs
      - home
      - opengl
      - removable-media
      - gsettings
      - network
      - browser-support
      - unity7
      - cups
      - shared-memory
    command-chain:
      - snap/command-chain/desktop-launch
  cmd:
    command: usr/bin/FreeCADCmd
    extensions: [kde-neon-6]
    plugs: *plugs
  pip:
    command: bin/pip
    plugs: *plugs

parts:
  stub-chown:
    plugin: meson
    source: $CRAFT_PROJECT_DIR/snap/local/stub-chown
    source-type: local
    build-packages:
    - meson
    meson-parameters:
      - --prefix=/usr

  snap-setup-mod:
    plugin: dump
    source: $CRAFT_PROJECT_DIR/snap/local/snap-setup-mod
    source-type: local
    organize:
      "*": usr/Mod/SnapSetup/

  freecad:
    plugin: cmake
    source: https://github.com/FreeCAD/FreeCAD.git
    cmake-parameters:
      - -DFREECAD_QT_VERSION=6
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_INSTALL_LIBDIR=lib
      - -DCMAKE_BUILD_TYPE=Release
      - -DPYTHON_EXECUTABLE=/usr/bin/python3
      - -DPYTHON_INCLUDE_DIR=/usr/include/python3.12
      - -DPYTHON_LIBRARY=/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libpython3.12.so
      - -DFREECAD_USE_PYBIND11=ON
      - -DFREECAD_USE_QT_FILEDIALOG=ON
      - -DBUILD_FLAT_MESH=ON
      - -DFREECAD_USE_PCL=OFF
    build-snaps:
      - freecad-deps-core24/edge
      - kde-pyside6-core24-sdk  # Provides the PySide/Shiboken SDK and runtime
    build-environment:
      - PYTHONPATH: /snap/kde-pyside6-core24-sdk/current/usr/lib/python3/dist-packages${PYTHONPATH:+:$PYTHONPATH}
      - LD_LIBRARY_PATH: /snap/kde-pyside6-core24-sdk/current/usr/lib:/snap/kde-pyside6-core24-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
      - CMAKE_PREFIX_PATH: /snap/kde-pyside6-core24-sdk/current/usr${CMAKE_PREFIX_PATH:+:$CMAKE_PREFIX_PATH}
      - PATH: /snap/kde-pyside6-core24-sdk/current/usr/bin${PATH:+:$PATH}
    stage-snaps:
      - freecad-deps-core24/edge
      - kde-pyside6-core24-sdk  # Provides the PySide/Shiboken SDK and runtime
    build-packages:
      # --- Build Toolchain ---
      - g++
      - git
      - swig

      # --- C++ Core & 3D Kernel Development Libraries ---
      - libboost-all-dev
      - libcoin-dev
      - libeigen3-dev
      - libfreeimage-dev
      - libgts-bin
      - libgts-dev
      - libkdtree++-dev
      - libmedc-dev
      - libopencv-dev
      - libproj-dev
      - libvtk9-dev
      - libx11-dev
      - libxerces-c-dev
      - libyaml-cpp-dev
      - swig
      - python3-dev
      - libcoin-dev
      - libvtk9-dev
      - pybind11-dev
      - python3-dev

      # --- Pre-packaged Build-Time Dependencies ---
      # These provide specific functionality during the build itself.
      - openscad
      - python3-lark
      - python3-pivy
      - python3-matplotlib
      - python3-pivy
      - python3-lark

    stage-packages:
      - libboost-regex1.83.0
      - libboost-system1.83.0
      - libboost-thread1.83.0
      - libboost-date-time1.83.0
#      - libilmbase25      # <= Unavailable in noble, still missing: libHalf, libIexMath
      - libmedc11t64
      - libmed11
      - on amd64: [libpsm-infinipath1]
      - libpython3.12
      - libpython3.12-stdlib
      - libxerces-c3.2t64
      - libyaml-cpp0.8
      - python3-yaml # FEM
      - python3-lark
      - python3-matplotlib
      - python3-opencamlib # CAM, experimental (https://wiki.freecad.org/OpenCamLib)
      - python3-setuptools-scm
      - python3-collada # DAE import
      - python3-git
      - python3-ply # OpenSCAD
      - python3-pivy
      - python3-requests
      - python3-vtk9 # FEM
      - calculix-ccx # FEM
      - libfreeimage3
      - openscad  # OpenSCAD
    override-build: |
      craftctl default
      sed -i -E \
        "s|^Icon=(.*)|Icon=\${SNAP}/usr/share/icons/hicolor/scalable/apps/org.freecad.FreeCAD.svg|g" \
        $CRAFT_PART_INSTALL/usr/share/applications/org.freecad.FreeCAD.desktop
      if [ "$CRAFT_ARCH_BUILD_FOR" = amd64 ]; then
        ln -sf ../libpsm1/libpsm_infinipath.so.1.16  $CRAFT_PART_INSTALL/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libpsm_infinipath.so.1
      fi
      cd $CRAFT_PART_SRC
      version_major=$(grep "set(PACKAGE_VERSION_MAJOR" CMakeLists.txt | tr -d '()"' | cut -d" " -f2)
      version_minor=$(grep "set(PACKAGE_VERSION_MINOR" CMakeLists.txt | tr -d '()"' | cut -d" " -f2)
      git_hash=$(git rev-parse --short=8 HEAD)
      version="${version_major}.${version_minor}-g$git_hash"
      craftctl set version="$version"

  python-packages:
    plugin: python
    source: .
    source-type: local
    python-requirements:
      - requirements.txt
    stage:
      - -pyvenv.cfg
      - -lib/python3.12/site-packages/scipy*
      - -lib/python3.12/site-packages/numpy*

  # The kf6-core24 snap provides the Qt6 libraries via the kde-neon-6 extension. However, it also
  # incidentally brings in graphviz. The graphviz installation in kf6-core24 is incomplete, missing
  # the generated config file. That installation also cannot be overriden, so we need to make it
  # work. The config file location is hardcoded into the graphviz binaries, thus we provide it
  # ourselves and tell graphviz where to find it via the the GVBINDIR environment variable in the
  # `freecad` part.
  #
  # This part creates a self-contained graphviz CLI runtime environment with all the necessary
  # plugins and the config file. The reason we need to provide the plugin libraries is that using
  # the GVBINDIR environment variable method we're employing expects both the config file and the
  # plugins to be in the same directory.
  graphviz-config:
    plugin: nil
    build-packages:
      - graphviz
    build-environment:
      - LD_LIBRARY_PATH: "" # Unset to avoid picking up the kf6-core24 libraries during build
    override-build: |
      # 1. Generate the config file using the binary from /usr/bin/dot.
      # This binary is provided by the build-packages: [graphviz] directive.
      dot -c

      # 2. Create the directory for the self-contained graphviz environment.
      mkdir -p $CRAFT_PART_INSTALL/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/graphviz-runtime

      # 3. Copy the generated config file into that directory.
      cp /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/graphviz/config6a \
         $CRAFT_PART_INSTALL/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/graphviz-runtime/

      # 4. Copy all the plugin libraries into that directory, making it self-sufficient.
      cp /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/graphviz/*.so* \
         $CRAFT_PART_INSTALL/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/graphviz-runtime/

  cleanup:
    after: [stub-chown, freecad, python-packages, snap-setup-mod, graphviz-config]
    plugin: nil
    build-snaps: [kf6-core24/beta]
    override-prime: |
      set -eux
      for snap in "kf6-core24"; do
        cd "/snap/$snap/current" && \
        find . -type f,l \
          -not -path "./usr/lib/python3/dist-packages/*" \
          -not -name 'libblas.so*' \
          -not -name 'liblapack.so*' \
          -not -name 'mca_*.so' \
          -not -name 'libmpi.so*' \
          -not -name 'libopen-rte.so*' \
          -not -name 'libopen-pal.so*' \
          -exec rm -f "$CRAFT_PRIME/{}" "$CRAFT_PRIME/usr/{}" \;
      done
      for cruft in bug lintian man; do
        rm -rf $CRAFT_PRIME/usr/share/$cruft
      done
      find $CRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -not -name 'ThirdPartyLibraries.html' -not -name 'LICENSE.html' -delete
      find $CRAFT_PRIME/usr/share -type d -empty -delete
      find $CRAFT_PRIME/usr/lib -type f,l \
        -name 'libQt*.so*' `# remove all Qt libs pulled in from Ubuntu repos` \
        -not -name 'libQt6Gamepad.so*' -delete `# for OpenSCAD`

lint:
  ignore:
    - library
