name: 'Publish PR from Command'

on:
  issue_comment:
    types: [created]

jobs:
  # This job acts as a gatekeeper. It checks the trigger conditions
  # and outputs the PR number for the other jobs.
  get_pr_data:
    # This job only runs if a maintainer/admin comments "/publish" on a pull request
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, '/publish') &&
      (github.actor_permissions == 'admin' || github.actor_permissions == 'write')
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.get_number.outputs.pr_number }}
    steps:
      - name: 'Add reaction to acknowledge command'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: 'rocket'
            });

      - name: 'Get PR number'
        id: get_number
        run: echo "pr_number=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT

  # This job's sole purpose is to call the reusable workflow.
  # It is replaced entirely by the content of that workflow file.
  publish:
    needs: get_pr_data
    uses: ./.github/workflows/reusable-publish.yml
    with:
      os: ubuntu-22.04
      # Get the PR number from the output of the 'get_pr_data' job
      release_channel: 'edge/pr-${{ needs.get_pr_data.outputs.pr_number }}'
    # 'secrets: inherit' is a safe way to pass all the caller's secrets
    # to the reusable workflow.
    secrets: inherit

  # This job runs only after the 'publish' job has succeeded.
  # It provides the final feedback on the PR.
  report_status:
    needs: [get_pr_data, publish]
    runs-on: ubuntu-latest
    steps:
      - name: 'Add "snap-published" label to PR'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ needs.get_pr_data.outputs.pr_number }}
        run: |
          gh pr edit ${PR_NUMBER} --add-label "snap-published"

      - name: 'Comment on PR with installation instructions'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ needs.get_pr_data.outputs.pr_number }}
        run: |
          snap_channel="edge/pr-${PR_NUMBER}"
          comment_body="A build for this PR has been published to the Snap Store.

          The recommended way to test this build is to use a parallel installation, which will not affect your existing \`freecad\` snap installation.

          ## Installation and Testing Instructions

          \`\`\`bash
          # (One-time setup) Enable the experimental parallel-instances feature in snapd.
          # You only need to run this command once on your system.
          sudo snap set system experimental.parallel-instances=true

          # Install this PR's snap alongside your current FreeCAD installation.
          # The instance will be named after the PR number.
          sudo snap install --channel=${snap_channel} freecad_pr${PR_NUMBER}

          # Run the newly installed PR build.
          freecad_pr${PR_NUMBER}

          # When you are finished testing, you can remove this specific build.
          sudo snap remove freecad_pr${PR_NUMBER}
          \`\`\`"
          gh pr comment ${PR_NUMBER} --body "$comment_body"
