name: Publish Toponaming

on:
  schedule:
    - cron: "0 0 * * *" # Every day at 0:00
  workflow_dispatch: # or manually
    
jobs:
  publish_amd64:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: install snapcraft
      run: sudo snap install snapcraft --classic
    - name: install yq
      run: sudo snap install yq
    - name: modify snapcraft.yaml
      run: yq -i '.parts.freecad.source-branch = "development/toponaming"' snap/snapcraft.yaml
    - name: build snap
      run: |
        sudo snapcraft --destructive-mode
        sudo rm -rf $HOME/.config/snapcraft
    - name: publish snap
      env:
        SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
      run: snapcraft upload --release='latest/edge/toponaming' freecad*.snap
